config/routes.rb
Rails.application.routes.draw do

  authenticated :user do
    root :to => "welcome#index"
  end

  unauthenticated :user do
    root :to => "welcome#index", as: 'unauthenticated_root'
  end

  devise_for :users #do 
  resources :items

  get 'items/:id/done', to: 'items#done', as: "item_done"
  get 'items/:id/redo', to: 'items#redo', as: "item_redo"

  resources :users, only: [:update, :show] # Not sure why this does not work.  Error in Application Layout.  If change to User_Path still has issues.
  
  get 'about' => 'welcome#about'

end

app/models/item.rb
# == Schema Information
#
# Table name: items
#
#  id         :integer          not null, primary key
#  name       :string
#  user_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  status     :string
#  expiration :datetime
#

class Item < ActiveRecord::Base
  belongs_to :user
  before_create :set_default_status, :set_expiration

  def status_done
    self.update_attributes(status: 'done')
  end

  def make_to_open
      self.update_attributes(status: 'open')
      self.update_attributes(expiration: Time.now + 7.days)
  end

  def days_left
  # ~~~~~~~~~ Note ~~~~~~~~~~~~~~~
    # Expiration date and created_at date could be different depending on if the user renewed the action time which resets the expiration date.  So Option 1 & 2 flawed

  # ~~~~~~~~~ Option 1 ~~~~~~~~~~~~~~~
    # if (7 - (DateTime.now.to_date - created_at.to_date).to_i)>0 
    #   7 - (DateTime.now.to_date - created_at.to_date).to_i 
    # else
    #   0
    # end 
  
  # ~~~~~~~~~ Option 2 ~~~~~~~~~~~~~~~
    # (7 - (DateTime.now.to_date - created_at.to_date).to_i)>0 ? (7 - (DateTime.now.to_date - created_at.to_date).to_i) : 0
  
  # ~~~~~~~~~ Option 3 ~~~~~~~~~~~~~~~
   ((expiration.to_date - DateTime.now.to_date).to_i) > 0 ?  (expiration.to_date - DateTime.now.to_date).to_i : 0
  end

  def formatted_expiration
    expiration.since(7.days).to_date.to_formatted_s(:long_ordinal)
  end

  private
  def set_default_status
    self.status = 'open'
  end

  def set_expiration
    # self.expiration = Time.now + 7.days
    self.expiration = self.created_at + 7.days
  end

  default_scope {order('expiration asc')} # ~~~~~~~~ Sorts by date.  Default scope is not a special method or gem.  Built in. ~~~~~~~~~~~~

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  name                   :string
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string
#  last_sign_in_ip        :string
#  confirmation_token     :string
#  confirmed_at           :datetime
#  confirmation_sent_at   :datetime
#  unconfirmed_email      :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#

class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
  has_many :items
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    items_path(resource.id)
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
    devise_parameter_sanitizer.for(:account_update) {|u| u.permit(:name, :email, :password, :password_confirmation, :current_password)}
  end

  
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
    @open_items = current_user.items.where("expiration > ? AND status = ?", DateTime.now, "open")
    @expired_items = current_user.items.where("expiration <= ? AND status = ?", DateTime.now, "open")
    @completed_items = current_user.items.where(status: "done")

  end

  def new
    @item=Item.new
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
  end

  def destroy
    @user = current_user
    @item = Item.find(params[:id])

    @open_items = current_user.items.where("expiration > ? AND status = ?", DateTime.now, "open")
    @expired_items = current_user.items.where("expiration <= ? AND status = ?", DateTime.now, "open")
    @completed_items = current_user.items.where(status: "done")

    if @item.destroy
      flash[:notice] = " To Do Item Successfully Deleted."
      # redirect_to items_path(@wiki)
    else
      flash[:error] = "There Was An Error Deleting Your To Do Item.  Please Try Again."
      # render :show
    end

    respond_to do |format|
      format.html
      format.js
    end
  end

  def update
    @item = Item.find(params[:id])
    if @item.update_attributes(item_params)
      redirect_to items_path, notice: "Item updated."
    else
      flash[:error] = "Error updating To Do item.  Please try again."
      render :new
    end
  end

  def create
    @item = Item.new(item_params)
    @item.user_id = current_user.id #Not sure why I use this instead of @user = User.find(params[:id])

    if @item.save
      redirect_to items_path, notice: "Item successfully saved."
    else
      flash[:error] = "Error adding you To Do item.  Please try again."
      render :new
    end
  end

  def done
    @item = Item.find(params[:id])
    @item.status_done
    redirect_to items_path
  end

  def redo
    @item = Item.find(params[:id])
    @item.make_to_open
    redirect_to items_path
  end

  private
  def item_params
    params.require(:item).permit(:name, :user_id, :status, :expiration)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @user = current_user
  end

  def update
    if current_user.update_attributes(user_params)
      flash[:notice] = "User information updated"
      redirect_to edit_user_registration_path
    else
      flash[:error] = "Invalid user information"
      redirect_to edit_user_registration_path
    end
  end

  def show
    @user = current_user
    @user = User.find(params[:id]) if params[:id]
    @items = @user.items
    # @items = Item.find(params[:id])
    # http://stackoverflow.com/questions/15693479/couldnt-find-user-with-id-activerecordrecordnotfound
    # http://stackoverflow.com/questions/30858104/couldnt-find-user-with-id-show
  end
end

private
def user_params
  params.require(:user).permit(:name)
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return '' if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    sentence = I18n.t('errors.messages.not_saved',
      count: resource.errors.count,
      resource: resource.class.model_name.human.downcase)

    html = <<-HTML
    <div class="alert alert-danger alert-block">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <h4>#{sentence}</h4>
      #{messages}
    </div>
    HTML

    html.html_safe
  end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/items/_done.html.erb
<li id=<%="item-#{item.id}"%>>  
  <%= item.name%> 

  <span class="pull-right"><%= link_to "Delete | ", item, method: :delete, remote: true %>                 
    <%= link_to "Do Again", item_redo_path(item) %>
    <br/>
  </span>
  <br/>
  <small class="pull-right">Deletion Date - <%= item.formatted_expiration %></small><!--  Really helpful date construct to add days in display using since -->
  <br/>
</li>

<br/>

app/views/items/_expired.html.erb
<li id=<%="item-#{item.id}"%>>  
  <%= item.name %> 
  
  <span class="pull-right"><%= link_to "Delete | ", item, method: :delete, remote: true%> 
    <%= link_to "Renew To Do", item_redo_path(item) %>
    <br/> 
  </span>
  <br/>

  <small class="pull-right">Expired On - <%= item.expiration.to_date.to_formatted_s(:long_ordinal)%></small>
  <br/>
</li>

<br/>

app/views/items/_open_item.html.erb
<li id=<%="item-#{item.id}"%>>  
  <%= item.name%> 
 
  <span class="pull-right"><%= link_to "Delete | ", item, method: :delete, remote: true%> 
  <%= link_to "Done", item_done_path(item) %>
  <br/>
  </span>
  <br/>

  <small class="pull-right">Expires - <%= item.expiration.to_date.to_formatted_s(:long_ordinal)%> - <%= item.days_left%> Days Left</small>
  <br/>  
</li>

<br/>

app/views/items/destroy.js.erb
$('#item-' +<%= @item.id %>).hide();

<% if @open_items.blank? %>
  $('#open_items_id').hide();
<% end %>

<% if @expired_items.blank? %>
  $('#expired_items_id').hide();
<% end %>

<% if @completed_items.blank? %>
  $('#completed_items_id').hide();
<% end %>

// Only works with Ajax delete.  Need this and the code in the index to work properly
<% if @expired_items.count == 0 || @completed_items.count == 0 %>
  $('#open_item_line').hide();
<% end %>
// Just not working

<% if @completed_items.blank? %>
  $('#expired_item_line').hide();
<%end%>

app/views/items/index.html.erb
<h1>List of My To Do Items</h1>
</br>
</br>
  <div class="row">
    <div class="col-md-12">
      <!-- Not Expired Open To Dos -->
      <% if @open_items.count > 0 %> <!-- Interesting construct to display only if it exists -->
        <div id="open_items_id"> <!-- Ajax id -->
          <h3>Current Open Items</h3>
          <div class="media">
          <div class="media-body lead">
            <ol start="1">
              <% @open_items.each do |item| %>
                <%= render partial: "items/open_item", locals: {item: item} %>
              <%end%>
            </ol>
          </div>
          </div>
        <!-- Horizontal Line Break -->
        <% if @expired_items.count > 0 || @completed_items.count > 0 %>
          <div id="open_item_line"><!-- Ajax id -->
            <hr>
          </div>
        <%end%>
        </div>
      <%end%>

      <!-- Expired Open To Dos -->
      <% if @expired_items.count >0 %> <!-- Had to use present? to verify if line and title should appear -->
        <div id="expired_items_id"> <!-- Ajax id -->
          <h3 class = "text-muted">Expired Open Items</h3>
          <h5 class = "text-muted">Will be deleted 7 days after expiration</h5>
          <div class="media">
          <div class="media-body lead text-muted">
            <ol start="1">
              <% @expired_items.each do |item| %>
                <%= render partial: "items/expired", locals: {item: item} %>
              <%end%>
            </ol>
          </div>
          </div>
        <!-- Horizontal Line -->
        <div id="expired_item_line"> <!-- Ajax id -->
          <% if @completed_items.count>0 %>
            <hr>
          <%end%>
        </div>
        </div>
      <%end%>

      <!-- Completed Items -->
      <% if @completed_items.count > 0 %>
        <div id="completed_items_id">
          <h3 class="text-muted">Completed Items</h3>
          <h5 class = "text-muted">Will be deleted 7 days after expiration</h5>
          <div class="media">
          <div class="media-body lead text-muted">
            <ol start="1">
              <% @completed_items.each do |item| %>
                <%= render partial: "items/done", locals: {item: item} %>
              <%end%>
            </ol>
          </div>
          </div>
        </div>
      <%end%>
      <br/>
      <%= button_to "Add New To Do", new_item_path, method: :get, class: 'btn btn-info btn-lg' %>
    </div>
</div>

app/views/items/new.html.erb
<h1>Add a New To Do Item</h1>
</br>

<%=form_for @item do |f| %>
      
      <div class="form-group">
        <%= f.label "Description" %>
        <%= f.text_field :name, class: 'form-control', placeholder: "Enter To Do Item" %>
      </div>
      <p>This item will expire 7 days from now, on <u><%=7.days.from_now.strftime("%B %d, %Y")%></u>.  It will be deleted permenantly 7 days after it expires <u><%=14.days.from_now.strftime("%B %d, %Y")%></u>.</p>
      </br>
      
      <div class="form-group">
        <%= f.submit "Save", class: 'btn btn-success' %>
      </div>
<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blocitoff</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div class="container">
    <ul class="nav nav-tabs">
        <li><%= link_to "Blocitoff", root_path %></li>
        <li><%= link_to "About", about_path %></li>
        <li>
          <% if current_user %> 
            <%= link_to "To Do List", items_path %>
          <%else%>        
            <%= link_to "To Do List", new_user_session_path, onclick: "alert('You need to log in to see To Do list.')" %>
          <%end%>
        </li>

        <div class="pull-right user-info">
          <% if current_user %>
            Hello <%= link_to current_user.name, user_path(current_user) %> |
            <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
          <% else %>
            <%= link_to "Sign In", new_user_session_path %> or
            <%= link_to "Sign Up", new_user_registration_path %>
          <% end %>
        </div>
    </ul>

    <% if flash[:notice] %>
      <div class="alert alert-success">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:notice] %>
      </div>
    <% elsif flash[:error] %>
      <div class="alert alert-danger">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:error] %>
      </div>
    <% elsif flash[:alert] %>
      <div class="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:alert] %>
      </div>
    <% end %>

    <%= yield %>
  </div>

</body>
</html>

app/views/users/show.html.erb
<h2>User Profile</h2>
</br>
<div class="row">
	<div class="col-md-8">

      <p>Name: <big class="text-primary"><%=current_user.name%></big></p>
  		<p>Email Address: <big class="text-primary"><%=current_user.email%></big></p>
  		<p>Member Since: <big class="text-primary"><%=current_user.created_at.to_date.to_formatted_s(:long_ordinal)%></big></p>
  		
  		<%= button_to "Edit Profile", edit_user_registration_path, method: :get, class: 'btn btn-info' %>
  		</br>
      <hr>

  		<h3>View My To Do List</h3>
      <p>Number of To Do Items: <big class="text-primary"> <%= @user.items.count %> </big></p>
  		<p>Number of To Do Items Completed: <big class="text-primary"> <%= @user.items.where(:status => "done").count%> </big></p>
  		<p>Number of Open To Do Items: <big class="text-primary"> <%= @user.items.where(:status => "open").count%></big></p>

  		<%= button_to "View To Do List", items_path, method: :get, class: 'btn btn-success' %>
  		</br>
      <hr>

		<h3>Cancel My Account</h3>
		<p>We are sorry to see you go. Please consider carefully this cannot be undone.</p>
		<%= button_to "Cancel Account", registration_path(:user), data: { confirm: "Are you sure you want to cancel your account?" }, method: :delete, class: 'btn btn-danger' %>

	</div>
</div>

app/views/welcome/about.html.erb
<h1>Welcome#about</h1>
<p>Find me in app/views/welcome/about.html.erb</p>

app/views/welcome/index.html.erb
<!DOCTYPE html>
<html>
</br>
	<div class="jumbotron text-center center-block">
	  <h1 class="text-center">Blocitoff</h1>
	  <h3 class="text-muted">A self-destructing to-do list to keep you focused on the things that really matter</h3>

    <% if current_user %>
      </br>
      <%= button_to "View To Do's", items_path, method: :get, class: 'btn btn-info btn-lg' %>
    <%else%>
  </br>
    <div class="row">
      <div class="col-md-6 text-center">
        <%= button_to "Sign Up", new_user_registration_path, method: :get, class: 'btn btn-info btn-lg' %>
      </div>
      <div class="col-md-6 text-center">
        <%= button_to "Sign In", new_user_session_path, method: :get, class: 'btn btn-warning btn-lg' %>
      </div>
    </div>
    <%end%>
	</div>

</html>